# Generated by Django 4.2.1 on 2023-05-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('base_img', models.TextField()),
                ('honered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('sign', models.CharField(max_length=20)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('base_img', models.TextField()),
                ('honered', models.BooleanField(default=False)),
            ],
        ),
    ]
