# Generated by Django 4.2.1 on 2023-05-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_markexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('base_img', models.TextField()),
            ],
        ),
    ]
